# Generated by Django 4.2.2 on 2023-07-03 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Scraper",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                ("steps", models.TextField()),
                ("case", models.CharField(max_length=200)),
                ("data", models.CharField(max_length=200)),
            ],
        ),
    ]
